name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: "22"   # match your Lambda runtime

      - name: Install zip
        run: sudo apt-get update && sudo apt-get install -y zip

      - name: Install dependencies
        run: npm ci   # installs node_modules at repo root

      - name: Create deployment zip (include handler + code + node_modules)
        run: |
          zip -r code.zip . \
            -x "code.zip" "*.git*" "*.log" "node_modules/.cache/*" ".github/*"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name "${{ secrets.LAMBDA_FUNCTION_NAME }}" \
            --zip-file fileb://code.zip

      - name: Wait for Lambda update to finish
        run: aws lambda wait function-updated --function-name "${{ secrets.LAMBDA_FUNCTION_NAME }}"

      - name: Update Lambda environment variables (safe JSON)
        run: |
          cat > env.json <<EOF
          {"Variables": {
            "MONGO_URI":"${{ secrets.MONGO_URI }}",
            "REDIS_HOST":"${{ secrets.REDIS_HOST }}",
            "REDIS_PORT":"${{ secrets.REDIS_PORT }}",
            "REDIS_USERNAME":"${{ secrets.REDIS_USERNAME }}",
            "REDIS_PASSWORD":"${{ secrets.REDIS_PASSWORD }}"
          }}
          EOF
          aws lambda update-function-configuration \
            --function-name "${{ secrets.LAMBDA_FUNCTION_NAME }}" \
            --environment file://env.json \
            --region us-east-1

      - name: Test deployed Lambda (invoke)
        run: |
          printf '{"httpMethod":"GET","path":"/"}' > payload.json
          aws lambda invoke \
            --function-name "${{ secrets.LAMBDA_FUNCTION_NAME }}" \
            --payload file://payload.json response.json \
            --cli-binary-format raw-in-base64-out --region us-east-1
          cat response.json || true
