name: Deploy Lambda Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install server dependencies
        working-directory: server
        run: npm ci

      - name: Install zip
        run: sudo apt-get update && sudo apt-get install -y zip

      - name: Create deployment zip (only server code)
        run: |
          cd server
          zip -r ../code.zip . -x "*.git*" "*.log" "node_modules/.cache/*"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name "${{ secrets.LAMBDA_FUNCTION_NAME }}" \
            --zip-file fileb://code.zip

      - name: Wait for Lambda update to finish
        run: |
          aws lambda wait function-updated \
            --function-name "${{ secrets.LAMBDA_FUNCTION_NAME }}"

      - name: Update Lambda environment variables
        run: |
          aws lambda update-function-configuration \
            --function-name "${{ secrets.LAMBDA_FUNCTION_NAME }}" \
            --environment "Variables={MONGO_URI=${{ secrets.MONGO_URI }},REDIS_HOST=${{ secrets.REDIS_HOST }},REDIS_PORT=${{ secrets.REDIS_PORT }},REDIS_USERNAME=${{ secrets.REDIS_USERNAME }},REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}}"
